const rawText = {
  "raw-0": "@media (min-width:992px) {html.w-mod-js:not(.w-mod-ix) [data-w-id=\"5688d7d9-6d15-3f37-8131-e8be09b8e9fa\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"cf1d3dc4-a54e-773c-276f-52cfbc4a1929\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"6edbdcda-b7a6-c67d-3d34-d671091daf17\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"b99e631c-6d9c-c51e-3482-ca9eee265a83\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"c1801c4c-21d4-6511-ee51-201ab4b1d1fb\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"2618a5d8-cab5-82ba-82fd-9838885456a2\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"37ccef0a-720f-03f7-18af-3c475af6356c\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"8cf9e924-9934-4d5e-a489-58354b927c81\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"1b39b2b6-1eac-7688-bd2b-5e16c81a7ce8\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"4198aa68-3777-29a6-8a82-ec2477dd5ee5\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"39f47d5a-1223-ee90-453b-63a0f06cbbd4\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"9c1c2636-75b4-763c-b450-7bbbe77e3539\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"c0474c52-aa42-adbc-dc62-982b53513ae8\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"cdfb6100-2f81-74c5-12b1-fc1af069914c\"] {opacity:0;}}",
  "raw-1": "!function(o,c){var n=c.documentElement,t=\" w-mod-\";n.className+=t+\"js\",(\"ontouchstart\"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+\"touch\")}(window,document);",
  "raw-2": "\n.swiper-testimonial-wrapper .swiper-slide.swiper-slide-active {\n    opacity: 1 !important;\n}\n.swiper-testimonial-wrapper .swiper-slide {\n    opacity: 0 !important;\n    transition: opacity 300ms ease-out, transform 300ms ease-out;\n\n}\n.swiper-slide {\n     height: auto !important;\n    }\n.swiper-pagination {\n    position: relative;\n}\n.swiper-pagination-bullet {\n    width: 0.8rem;\n    height: 0.8rem;\n    background: #D4D2D8;\n    opacity: 1;\n}\n.swiper-pagination-bullet-active {\n    background: #131116;\n}\n",
  "raw-3": "\n  html { font-size: 1.25rem; }\n  @media screen and (max-width:1920px) { html { font-size: 1.25rem; } }\n  @media screen and (max-width:1440px) { html { font-size: calc(0.4482182628062361rem + 0.8908685968819599vw); } }\n  @media screen and (max-width:991px) { html { font-size: calc(0.5255847953216375rem + 1.1695906432748537vw); } }\n  @media screen and (max-width:478px) { html { font-size: 1.125rem; } }\n  @media screen and (max-width:375px) { html { font-size: calc(0.9996657754010695rem + 0.53475935828877vw); } }\n",
  "raw-4": "\n/* Gets rid of top margin on first element in any rich text*/\n.w-richtext>:first-child {\n\tmargin-top: 0;\n}\n/* Fets rid of bottom margin on last element in any rich text*/\n.w-richtext>:last-child, .w-richtext ol li:last-child, .w-richtext ul li:last-child {\n\tmargin-bottom: 0;\n}\n/* Prevents all click and hover interaction with an element */\n.is-clickable-off {\n\tpointer-events: none;\n}\n/* Enables you to add class of div-square which creates and maintains a 1:1 dimension of a div.*/\n.is-square::after {\n\tcontent: \"\";\n\tdisplay: block;\n\tpadding-bottom: 100%;\n}\n/* Hide focus outline for main content element */\nmain:focus-visible {\n\toutline: -webkit-focus-ring-color auto 0px;\n  outline: none;\n}\n/* Reset buttons, and links styles */\na {\n\tcolor: inherit;\n\ttext-decoration: inherit;\n\tfont-size: inherit;\n}\n/* Webkit Style reset for inputs  */  \ninput {   \n    -webkit-appearance: none;\n    -moz-appearance: none;\n    appearance: none;\n}\n/* Font Smoothing */\n* {\n\t\t-webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n\t}\n/* disable default arrows on select form fields */\n.w-select {\n    -webkit-appearance: none;\n    -moz-appearance: none;\n}\n.specialties-tab-link.w--current .tab-menu-chevron {\n    background-color: var(--color--grey-900);\n}\n.specialties-tab-link.w--current .tab-menu-chevron .chevron-on-tab {\n    transform: rotate(180deg);\n}\n\n",
  "raw-5": "\nhtml.wf-design-mode [href=\"#\"] {\n\toutline: 3px solid yellow !important;\n}\n",
  "raw-6": "{\n  \"items\": [\n    {\n      \"url\": \"https://www.youtube.com/watch?v=GtXYKMA3dHs\",\n      \"originalUrl\": \"https://www.youtube.com/watch?v=GtXYKMA3dHs\",\n      \"width\": 940,\n      \"height\": 528,\n      \"thumbnailUrl\": \"https://i.ytimg.com/vi/GtXYKMA3dHs/hqdefault.jpg\",\n      \"html\": \"<iframe class=\\\"embedly-embed\\\" src=\\\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FGtXYKMA3dHs%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGtXYKMA3dHs&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FGtXYKMA3dHs%2Fhqdefault.jpg&key=96f1f04c5f4143bcb0f2e68c87d65feb&type=text%2Fhtml&schema=youtube\\\" width=\\\"940\\\" height=\\\"528\\\" scrolling=\\\"no\\\" title=\\\"YouTube embed\\\" frameborder=\\\"0\\\" allow=\\\"autoplay; fullscreen; encrypted-media; picture-in-picture;\\\" allowfullscreen=\\\"true\\\"></iframe>\",\n      \"type\": \"video\"\n    }\n  ],\n  \"group\": \"\"\n}",
  "raw-7": "{\n  \"items\": [\n    {\n      \"url\": \"https://www.youtube.com/watch?v=GtXYKMA3dHs\",\n      \"originalUrl\": \"https://www.youtube.com/watch?v=GtXYKMA3dHs\",\n      \"width\": 940,\n      \"height\": 528,\n      \"thumbnailUrl\": \"https://i.ytimg.com/vi/GtXYKMA3dHs/hqdefault.jpg\",\n      \"html\": \"<iframe class=\\\"embedly-embed\\\" src=\\\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FGtXYKMA3dHs%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGtXYKMA3dHs&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FGtXYKMA3dHs%2Fhqdefault.jpg&key=96f1f04c5f4143bcb0f2e68c87d65feb&type=text%2Fhtml&schema=youtube\\\" width=\\\"940\\\" height=\\\"528\\\" scrolling=\\\"no\\\" title=\\\"YouTube embed\\\" frameborder=\\\"0\\\" allow=\\\"autoplay; fullscreen; encrypted-media; picture-in-picture;\\\" allowfullscreen=\\\"true\\\"></iframe>\",\n      \"type\": \"video\"\n    }\n  ],\n  \"group\": \"\"\n}",
  "raw-8": " ul.specialties-features-list li::marker {color: #BBF516;}\nul.specialties-features-list li.nested-feature-list-item::marker {color: white;}",
  "raw-9": "\n      $(document).ready(()=>{\n            let isMenuAlreadyOpen = false;\n            $('.menu-button').on('click',()=>{\n                  $('body').css(\"overflow\",isMenuAlreadyOpen?\"auto\":\"hidden\")\n                  isMenuAlreadyOpen = !isMenuAlreadyOpen\n            })\n      })\n",
  "raw-10": "\n\tconst isStaging = window.location.search.includes('?dev');\n    const script = document.createElement('script');\n    script.src = isStaging\n        ? '/vendor/flow.js'\n        : '/vendor/flow.js';\n    script.defer = true;\n    document.body.appendChild(script);\n",
  "raw-11": "\n$(document).ready(function() {\n    // Function to check screen width and scroll to the top if it's 992px or wider\n    function checkAndScroll() {\n        if ($(window).width() >= 992) {\n            $('html, body').scrollTop(0);\n        }\n    }\n\n    // Scroll to the top when the page is loaded, if the screen width is 992px or wider\n    $(window).on('load', checkAndScroll);\n\n    // Scroll to the top when the browser window is resized and width is 992px or wider\n    $(window).on('resize', checkAndScroll);\n});\n\n\n",
  "raw-12": "\nfunction equalizeTabCardTitles() {\n    var maxHeight = 0;\n\n    // Reset all heights to auto to get the natural height\n    $('.blog-card-title').css('height', 'auto');\n\n    // Calculate the maximum height\n    $('.blog-card-title').each(function() {\n        var thisHeight = $(this).outerHeight();\n        if (thisHeight > maxHeight) {\n            maxHeight = thisHeight;\n        }\n    });\n\n    // Set all to the maximum height\n    $('.blog-card-title').height(maxHeight);\n}\n\n// Run on document ready and on window resize\n$(document).ready(function() {\n    equalizeTabCardTitles(); // Equalize heights on page load\n    $(window).resize(function() {\n        equalizeTabCardTitles(); // Equalize heights whenever window is resized\n    });\n});\n\ndocument.addEventListener('DOMContentLoaded', function() {\n  var swiper = new Swiper(\".swiper-testimonial-wrapper\", {\n    spaceBetween: 0,\n    effect: \"fade\",\n    loop: true,\n    navigation: {\n      nextEl: \".swiper-right\",\n      prevEl: \".swiper-left\",\n    },\n    // Default pagination setting for mobile views\n    pagination: {\n      el: \".testimonial-pagination\",\n      clickable: true,\n    },\n    breakpoints: {\n      // Breakpoint for desktop views\n      992: {\n        pagination: false  // Disable pagination for views 992 pixels and above\n      }\n    }\n  });\n});\n\n\ndocument.addEventListener('DOMContentLoaded', function() {\n  var swiper = new Swiper(\".latest-blog-carousel\", {\n    spaceBetween: 24,\n    loop: false,\n    slidesPerView: 1,  // Default number of slides for larger screens\nslidesPerGroup: 1,\n    pagination: {\n      el: \".swiper-pagination\",\n      clickable: true,\n    },\n    breakpoints: {\n      // When the viewport is less than 992 pixels, the settings will change\n      991: {\n        slidesPerView: 3,  // For example, show 2 slides per view on smaller screens\n        navigation: {\n      nextEl: \".blog-right\",\n      prevEl: \".blog-left\",\n    },\n      }\n    }\n  });\n});\n\n\n\n\n"
} as const

export const pageCode = {
  initialInteractionStyles: rawText['raw-0'],
  webflowBootstrap: rawText['raw-1'],
  carouselStyles: rawText['raw-2'],
  responsiveTypeStyles: rawText['raw-3'],
  utilityStyles: rawText['raw-4'],
  designerDebugStyles: rawText['raw-5'],
  primaryLightboxConfig: rawText['raw-6'],
  secondaryLightboxConfig: rawText['raw-7'],
  specialtiesListStyles: rawText['raw-8'],
  mobileMenuBehavior: rawText['raw-9'],
  flowRuntimeLoader: rawText['raw-10'],
  desktopScrollReset: rawText['raw-11'],
  carouselBehavior: rawText['raw-12'],
} as const
