export const sitePageCode = {
  productsAppetite: [
    "@media (min-width:992px) {html.w-mod-js:not(.w-mod-ix) [data-w-id=\"5688d7d9-6d15-3f37-8131-e8be09b8e9fa\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"cf1d3dc4-a54e-773c-276f-52cfbc4a1929\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"6edbdcda-b7a6-c67d-3d34-d671091daf17\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"c0474c52-aa42-adbc-dc62-982b53513ae8\"] {opacity:0;}}",
    "!function(o,c){var n=c.documentElement,t=\" w-mod-\";n.className+=t+\"js\",(\"ontouchstart\"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+\"touch\")}(window,document);",
    "\n.drop-sub {\n    top: 8rem !important;\n}\n\n@media screen and (max-width: 991px) {\n    .drop-sub {\n        position: relative;\n        top: 0 !important;\n    }\n}\n",
    "\n      $(document).ready(()=>{\n            let isMenuAlreadyOpen = false;\n            $('.menu-button').on('click',()=>{\n                  $('body').css(\"overflow\",isMenuAlreadyOpen?\"auto\":\"hidden\")\n                  isMenuAlreadyOpen = !isMenuAlreadyOpen\n            })\n      })\n",
    "\n\tconst isStaging = window.location.search.includes('?dev');\n    const script = document.createElement('script');\n    script.src = isStaging\n        ? '/vendor/flow.js'\n        : '/vendor/flow.js';\n    script.defer = true;\n    document.body.appendChild(script);\n",
    "\n$(document).ready(function() {\n    // Function to check screen width and scroll to the top if it's 992px or wider\n    function checkAndScroll() {\n        if ($(window).width() >= 992) {\n            $('html, body').scrollTop(0);\n        }\n    }\n\n    // Scroll to the top when the page is loaded, if the screen width is 992px or wider\n    $(window).on('load', checkAndScroll);\n\n    // Scroll to the top when the browser window is resized and width is 992px or wider\n    $(window).on('resize', checkAndScroll);\n});\n\n\n",
  ],
  retailBrokers: [
    "@media (min-width:992px) {html.w-mod-js:not(.w-mod-ix) [data-w-id=\"5688d7d9-6d15-3f37-8131-e8be09b8e9fa\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"cf1d3dc4-a54e-773c-276f-52cfbc4a1929\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"6edbdcda-b7a6-c67d-3d34-d671091daf17\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"c0474c52-aa42-adbc-dc62-982b53513ae8\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"700514c9-05ab-d5ee-63c4-eca1f74eeaaf\"] {opacity:0;}}",
    "!function(o,c){var n=c.documentElement,t=\" w-mod-\";n.className+=t+\"js\",(\"ontouchstart\"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+\"touch\")}(window,document);",
    "\n      $(document).ready(()=>{\n            let isMenuAlreadyOpen = false;\n            $('.menu-button').on('click',()=>{\n                  $('body').css(\"overflow\",isMenuAlreadyOpen?\"auto\":\"hidden\")\n                  isMenuAlreadyOpen = !isMenuAlreadyOpen\n            })\n      })\n",
    "\n\tconst isStaging = window.location.search.includes('?dev');\n    const script = document.createElement('script');\n    script.src = isStaging\n        ? '/vendor/flow.js'\n        : '/vendor/flow.js';\n    script.defer = true;\n    document.body.appendChild(script);\n",
    "\n$(document).ready(function() {\n    // Function to check screen width and scroll to the top if it's 992px or wider\n    function checkAndScroll() {\n        if ($(window).width() >= 992) {\n            $('html, body').scrollTop(0);\n        }\n    }\n\n    // Scroll to the top when the page is loaded, if the screen width is 992px or wider\n    $(window).on('load', checkAndScroll);\n\n    // Scroll to the top when the browser window is resized and width is 992px or wider\n    $(window).on('resize', checkAndScroll);\n});\n\n\n",
  ],
  carriers: [
    "@media (min-width:992px) {html.w-mod-js:not(.w-mod-ix) [data-w-id=\"5688d7d9-6d15-3f37-8131-e8be09b8e9fa\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"cf1d3dc4-a54e-773c-276f-52cfbc4a1929\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"6edbdcda-b7a6-c67d-3d34-d671091daf17\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"c0474c52-aa42-adbc-dc62-982b53513ae8\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"700514c9-05ab-d5ee-63c4-eca1f74eeaaf\"] {opacity:0;}}",
    "!function(o,c){var n=c.documentElement,t=\" w-mod-\";n.className+=t+\"js\",(\"ontouchstart\"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+\"touch\")}(window,document);",
    "\n      $(document).ready(()=>{\n            let isMenuAlreadyOpen = false;\n            $('.menu-button').on('click',()=>{\n                  $('body').css(\"overflow\",isMenuAlreadyOpen?\"auto\":\"hidden\")\n                  isMenuAlreadyOpen = !isMenuAlreadyOpen\n            })\n      })\n",
    "\n\tconst isStaging = window.location.search.includes('?dev');\n    const script = document.createElement('script');\n    script.src = isStaging\n        ? '/vendor/flow.js'\n        : '/vendor/flow.js';\n    script.defer = true;\n    document.body.appendChild(script);\n",
    "\n$(document).ready(function() {\n    // Function to check screen width and scroll to the top if it's 992px or wider\n    function checkAndScroll() {\n        if ($(window).width() >= 992) {\n            $('html, body').scrollTop(0);\n        }\n    }\n\n    // Scroll to the top when the page is loaded, if the screen width is 992px or wider\n    $(window).on('load', checkAndScroll);\n\n    // Scroll to the top when the browser window is resized and width is 992px or wider\n    $(window).on('resize', checkAndScroll);\n});\n\n\n",
  ],
  aboutUs: [
    "@media (min-width:992px) {html.w-mod-js:not(.w-mod-ix) [data-w-id=\"5688d7d9-6d15-3f37-8131-e8be09b8e9fa\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"cf1d3dc4-a54e-773c-276f-52cfbc4a1929\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"6edbdcda-b7a6-c67d-3d34-d671091daf17\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"c0474c52-aa42-adbc-dc62-982b53513ae8\"] {opacity:0;}}",
    "!function(o,c){var n=c.documentElement,t=\" w-mod-\";n.className+=t+\"js\",(\"ontouchstart\"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+\"touch\")}(window,document);",
    "\n      $(document).ready(()=>{\n            let isMenuAlreadyOpen = false;\n            $('.menu-button').on('click',()=>{\n                  $('body').css(\"overflow\",isMenuAlreadyOpen?\"auto\":\"hidden\")\n                  isMenuAlreadyOpen = !isMenuAlreadyOpen\n            })\n      })\n",
    "\n\tconst isStaging = window.location.search.includes('?dev');\n    const script = document.createElement('script');\n    script.src = isStaging\n        ? '/vendor/flow.js'\n        : '/vendor/flow.js';\n    script.defer = true;\n    document.body.appendChild(script);\n",
    "\n$(document).ready(function() {\n    // Function to check screen width and scroll to the top if it's 992px or wider\n    function checkAndScroll() {\n        if ($(window).width() >= 992) {\n            $('html, body').scrollTop(0);\n        }\n    }\n\n    // Scroll to the top when the page is loaded, if the screen width is 992px or wider\n    $(window).on('load', checkAndScroll);\n\n    // Scroll to the top when the browser window is resized and width is 992px or wider\n    $(window).on('resize', checkAndScroll);\n});\n\n\n",
  ],
  getInTouch: [
    "@media (min-width:992px) {html.w-mod-js:not(.w-mod-ix) [data-w-id=\"d6ec158b-413a-2252-c730-9e6331badb22\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"0c45a849-9c8e-3fe9-b20e-34dfaac634ba\"] {opacity:0;}html.w-mod-js:not(.w-mod-ix) [data-w-id=\"850cdf28-50b2-a4dc-dddb-3c8bb97ffb23\"] {opacity:0;}}",
    "!function(o,c){var n=c.documentElement,t=\" w-mod-\";n.className+=t+\"js\",(\"ontouchstart\"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+\"touch\")}(window,document);",
    "\n      $(document).ready(()=>{\n            let isMenuAlreadyOpen = false;\n            $('.menu-button').on('click',()=>{\n                  $('body').css(\"overflow\",isMenuAlreadyOpen?\"auto\":\"hidden\")\n                  isMenuAlreadyOpen = !isMenuAlreadyOpen\n            })\n      })\n",
    "\n\tconst isStaging = window.location.search.includes('?dev');\n    const script = document.createElement('script');\n    script.src = isStaging\n        ? '/vendor/flow.js'\n        : '/vendor/flow.js';\n    script.defer = true;\n    document.body.appendChild(script);\n",
    "\n$(document).ready(function() {\n    // Function to check screen width and scroll to the top if it's 992px or wider\n    function checkAndScroll() {\n        if ($(window).width() >= 992) {\n            $('html, body').scrollTop(0);\n        }\n    }\n\n    // Scroll to the top when the page is loaded, if the screen width is 992px or wider\n    $(window).on('load', checkAndScroll);\n\n    // Scroll to the top when the browser window is resized and width is 992px or wider\n    $(window).on('resize', checkAndScroll);\n});\n\n\n",
  ],
} as const
